repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
  -   id: end-of-file-fixer
  -   id: trailing-whitespace

- repo: local
  hooks:
    - id: test-hook
      name: Run Pytest with Linters
      entry: bash -c 'poe test-lint'
      language: system

- repo: https://github.com/compilerla/conventional-pre-commit
  rev: v1.2.0
  hooks:
    - id: conventional-pre-commit
      stages: [commit-msg]
