# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Deta Deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    if: |
      contains(github.event.head_commit.message, 'feat')
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.9"]
      fail-fast: false
    steps:
    - name: Install Deta CLI
      shell: bash
      run: |
        curl -fsSL https://get.deta.dev/cli.sh | sh
    - name: Clone Deta Metadata
      shell: bash
      run: |
        export DETA_ACCESS_TOKEN=${{ secrets.DETA_TOKEN }}
        cd src
        ~/.deta/bin/deta clone --name deta-deployment tmp/
        cp -r tmp/.deta .
    - name: Deploy to Deta
      shell: bash
      run: |
        export DETA_ACCESS_TOKEN=${{ secrets.DETA_TOKEN }}
        cd src
        ~/.deta/bin/deta deploy

