# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Test and Deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    if: |
      ! contains(github.event.head_commit.message, 'docs') && 
      ! contains(github.event.head_commit.message, 'chore') 
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.9"]
      fail-fast: false
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0 
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install poetry poethepoet
        poetry install
    - name: Build and install the library
      run: |
        poe build
    - name: Test with pytest
      run: |
        export PYTHONPATH=$(pwd)/src
        poe test
    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.ACTIONS_TOKEN }}  # Needed to get PR information, if any
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    - name: Install Deta CLI
      shell: bash
      run: |
        curl -fsSL https://get.deta.dev/cli.sh | sh
    - name: Clone Deta Metadata
      shell: bash
      run: |
        export DETA_ACCESS_TOKEN=${{ secrets.DETA_TOKEN }}
        cd src
        ~/.deta/bin/deta clone --name deta-deployment tmp/
        cp -r tmp/.deta .
    - name: Deploy to Deta
      shell: bash
      run: |
        export DETA_ACCESS_TOKEN=${{ secrets.DETA_TOKEN }}
        cd src
        ~/.deta/bin/deta deploy
  
